name: Build & Deploy anime1 show list page

on:
    schedule:
        - cron: "0 4 * * *"
        - cron: "0 16 * * *"
    push:
        branches:
            -   master
    pull_request:
        branches:
            -   master
jobs:
    deploy:
        runs-on: macos-latest
        permissions:
            contents: write
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Set Node version
                uses: actions/setup-node@v4
                with:
                    node-version-file: '.nvmrc'
            -   name: Build
                shell: bash
                run: |
                    yarn install --frozen-lockfile;
                    yarn build INPUT=src/index.ts;
            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./dist
